application: quixotic-strand-716
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /groups.*
  script: groups.app
  login: required

- url: /posts.*
  script: posts.app
  login: required

- url: /feeds.*
  script: feeds.app
  login: required

- url: /static
  static_dir: static


libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
